language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.14/bin/
  - export CHROME_BIN #=chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - pip install selenium==2.48.0
  #- python example_project/manage.py collectstatic --noinput --settings test_settings
script:
  - make test
  - make lint
  # after success
  # - make docker_b uild
  # - make docker_push
